### ISSUE TITLE
As a student I want a login so that I may take the survey and only have to enter survey responses and not have to reenter my name teacher counselor

### ISSUE THREAD

**Issue by jschwarzwalder** [TeamBlue-IT355/emotion-counts#10]
Having a similar login as the student would be great!
ggreco
6 number password

This would be created by the Administration or Teacher

**Comment by jschwarzwalder** [comment]
"As a Student I want a login so that I may access a survey for ME"

**Comment by baarnold** [comment]
Claimed by Benjamin Arnold

**Comment by baarnold** [comment]
Given a student wants to take the test, When they go to the website, then they can take the survey.
Given  a student is in the class, When they need to take the survey, Then they can log in to their account to do so.
Given a classroom of students, When any student needs to take the survey, Then they can only log in to their account and no one else's.
