### ISSUE TITLE
As a visitor, I want to see a description of the website, so that I know why Emotions Count is important.

### ISSUE THREAD

**Issue by baarnold** [TeamBlue-IT355/emotion-counts#13]
Acceptance  criteria: Given that I am a general user  When I go to the url for the survey then I should see a paragraph of text that explains why Emotion Count is Important.

- [x]  Index page should include paragraph about why Emotion Counts is Important #14

**Comment by jschwarzwalder** [comment]
Technical Requirement - Index page should include paragraph about why Emotion Counts is Important

**Comment by jschwarzwalder** [comment]
- [ ]  Index page should include paragraph about why Emotion Counts is Important

**Comment by jschwarzwalder** [comment]
- [ ] 

- [ ]

**Comment by jschwarzwalder** [comment]
For now, can we have a basic navigation bar near the top with Home, About Us, Video Tutorials, Video Resources, Student Login, Teacher Login & Message Board (to communicate with parents)

Then somewhere on the homepage can we have the "Begin Survey" button? I still like the video idea on the home page too but with kids explaining. This would only be the first time the kids took the survey if possible, not every time.
