### ISSUE TITLE
As a student I want to be able to enter my answers to the survey and remember what I successfully entered so that if I enter something wrong or have to go back a page I do not need to reenter all my responses

### ISSUE THREAD

**Issue by jschwarzwalder** [TeamBlue-IT355/emotion-counts#3]

**Comment by nsama86** [comment]
Acceptance Criteria:

Given that a student wants to change an answer.
When the user navigates between questions.
Then it is expected that the questions that the student has answered will retain their previous answers.

- [ ] Session holds information of all answers until submission. 
- [ ] User is able to go back and forth between all questions before submission and not lose any data while going back and forth.

**Comment by nsama86** [comment]
Claimed by Josh
