### ISSUE TITLE
As a counselor I want a page to access a table of students I work with and their latest survey response so that I can see the results and responses

### ISSUE THREAD

**Issue by jschwarzwalder** [TeamBlue-IT355/emotion-counts#5]
Acceptance Criteria
Given… when… then…

Technical Tasks
- [ ] HTML/PHP/jQuery table displaying students and tests
- [ ] Table queries MySQL Database for latest test results from students
- [ ] Table shows only last test taken by each unique student
- [ ]  Passes HTML Validation
- [ ] Works in all browsers (Chrome, IE, Mozilla)

**Comment by baarnold** [comment]
Claimed by the Benjamin Hegemony
