### ISSUE TITLE
As a student after I have selected an answer on the survey I want the submit button to turn green so that I know I have answered all the questions

### ISSUE THREAD

**Issue by jschwarzwalder** [TeamBlue-IT355/emotion-counts#55]
- [x] Button will not be green when question is not answered
- [x] When question has been answered submit button turns green
- [ ] Page passes html validator
- [x] Javascript is hosted locally so not stopped by whitelist
- [x]  Test that it works in IE
- [x]  Test that it works in Mozilla
- [x]  Test that it works in Chrome
- [x]  Test that it works in Opera

Given I am a  Student when I answer all the questions then  the submit button will change to  green 

Given I am a student when I first see the question then the submit button should not be green

**Comment by Satinderk** [comment]
I can save my answers.

**Comment by Satinderk** [comment]
I can see all the questions are answered.

**Comment by Satinderk** [comment]
I also can see the submit button to be green when I answered all the questions.
