### ISSUE TITLE
As a counselor I want a secure login so that only I can see the results for the students I work with and child's trust and privacy is maintained

### ISSUE THREAD

**Issue by jschwarzwalder** [TeamBlue-IT355/emotion-counts#6]
Acceptance Criteria
Given that I'm a counselor with students who will take the survey when I go to emotions count then I should have a unique login as a counselor

Technical Tasks
- [ ] create counselor role in database
- [ ] create counselor column in student table
- [ ] create account for testing
- [ ] assign student to counselor

**Comment by nsama86** [comment]
I, Joshua Hawks, claim this sprint goal.
