### ISSUE TITLE
As a website visitor I want a top navigation so that I can learn about emotion counts without creating an account

### ISSUE THREAD

**Issue by jschwarzwalder** [TeamBlue-IT355/emotion-counts#60]
For now, can we have a basic navigation bar near the top with Home, About Us, Video Tutorials, Video Resources, Student Login, Teacher Login & Message Board (to communicate with parents)

Then somewhere on the homepage can we have the "Begin Survey" button? I still like the video idea on the home page too but with kids explaining. This would only be the first time the kids took the survey if possible, not every time.

**Comment by jschwarzwalder** [comment]
-  [ ] Each page has top navigation for site
-  [ ] Links on navbar go to the correct page
-  [ ]  navigation displays properly on mobile devices
-  [ ]  titles in navigation are easy for kids to understand where they should click
-  [ ]

**Comment by nsama86** [comment]
Josh claims this task.

**Comment by nsama86** [comment]
Acceptance Criteria:

Given that a visitor wants to navigate and view information about the site.
When the visitor visits the site to navigate its pages.
Then it is expected that all links work correctly and that the visitor is able to navigate the site as expected in areas that they are allowed to access.
