### ISSUE TITLE
As a teacher I want to print information about a child's responses so I can share with a parent at home

### ISSUE THREAD

**Issue by jschwarzwalder** [TeamBlue-IT355/emotion-counts#7]
Acceptance Criteria
Given...when...then...

Technical Tasks
[] Task 1

**Comment by Satinderk** [comment]
Acceptance Criteria
Given the completed answers when the children completed their survey then I can print their results/answers for their parents.

Technical Tasks
[] A button to print the answers
[] Fetch the data / responses from The DataBase
[] Create print list
[] Works all in the browsers

**Comment by Satinderk** [comment]
Claimed by Satinder Kainth
